version: '3'
networks:
  db-data-net:
    driver: bridge
services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp:2.0.0
    container_name: django-app
    ports: 
      - "8080:8080"
    environment:
      - ENV=local
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: mysql-local:1.0.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net
volumes:
  db-data: